### ISSUE TITLE
ViewHolderManager能否提供视图销毁方法

### ISSUE THREAD

**Issue by williamwue** [free46000/MultiItem#8]
目前ViewHolderManager仅提供了绑定数据方法onBindViewHolder，能否也提供视图销毁方法，比如如果要在BaseViewHolderManager中异步加载网络图像的话，就需要在视图销毁时能及时停止并销毁异步加载进程，或者有什么其他解决方案吗？

**Comment by free46000** [comment]
在滚动过程中，是一直在复用的，视图销毁应该是在`activity finish`之后

如果只是需要解决`ViewHolder`中含有图像视图的情况，需要你在`onBindViewHolder`中先去停止销毁正在异步加载中的线程，然后在为这个图像视图开启新的异步加载线程

不知道这样能否解答你的问题
